language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t amyl/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amyl/docker-react npm run test -- --coverage
